version: '3.4'

services:
  tunder:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44352
    ports:
      - "35396:80"
      - "44352:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    image: ${DOCKER_REGISTRY}tunder
    build:
      context: .
      dockerfile: Tunder.API/Dockerfile
    depends_on:
            - db
  db:
    image: "microsoft/mssql-server-linux"
    build:
      context: .
      dockerfile: infra/mssql/Dockerfile     
    environment:
      SA_PASSWORD: "BonjourMadame69"
      ACCEPT_EULA: "Y"
    ports:
      - target: 1433
        published: 1433
